name: {{ cookiecutter.conda_environment_name }}

channels:
  - esri
  - conda-forge

dependencies:
  - arcgis==1.8.2
  - cookiecutter
  - dask
 # - fastai==1.0.54
  - h3-py
  - jupyterlab
 # - keras-gpu==2.2.4
  - mkdocs
 # - pillow==6.1.0
  - pip
  - progress
  - pylint
  - pytest
  - python-dotenv
 # - pytorch==1.1.0
  - pyyaml
  - scipy
 # - scikit-image==0.15.0
  - scikit-learn
  - seaborn
  - shapely
  - swifter
 # - tensorflow-gpu==1.14.0
  - tqdm
  - pip:
    - azure-storage-blob
    - ipykernel
    - pyarrow
    - sphinx
    - sphinx-autodoc-typehints
    - sphinx_rtd_theme
