package:
  name: ba-tools
  version: "0.6.3"

source:
  path: ./

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python>=3.6
    - setuptools
  run:
    - python>=3.6
    - requests
    - numpy
    - pandas
    - arcgispro
    - arcgis>=1.6.1
    - scikit-learn

about:
  home: https://github.com/knu2xs/ba-tools
  license: Apache 2.0
  license_file: LICENSE
  summary: "Address business challenges using quantitative geographic and machine learning methods."
  doc_source_url: https://github.com/knu2xs/ba-tools/blob/master/README.md
