package:
  name: ba-tools
  version: "0.7.9"

source:
  path: ..

build:
  preserve_egg_dir: True
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python>=3.6
    - setuptools
  run:
    - arcgis>=1.7.0
    - numpy
    - pandas
    - requests
    - scikit-learn

about:
  home: https://github.com/knu2xs/ba-tools
  license: Apache 2.0
  license_file: LICENSE
  summary: "Address business challenges using quantitative geographic and machine learning methods."
  dev_url: https://github.com/knu2xs/ba-tools
  doc_url: https://github.com/knu2xs/ba-tools/blob/master/README.md
  doc_source_url: https://github.com/knu2xs/ba-tools/blob/master/README.md
