# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# D:\projects\ba-tools\conda_recipe, last modified Wed Nov  6 16:55:04 2019
# ------------------------------------------------

package:
    name: ba-tools
    version: 0.7.1
source:
    path: D:\projects\ba-tools
build:
    preserve_egg_dir: true
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: '0'
requirements:
    build:
        - certifi 2019.9.11 py36_0
        - pip 19.3.1 py36_0
        - python 3.6.9 1
        - setuptools 41.6.0 py36_1
        - sqlite 3.30.1 hfa6e2cd_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_0
        - wheel 0.33.6 py36_0
        - wincertstore 0.2 py36_1003
    run:
        - arcgis>=1.7.0
        - numpy
        - pandas
        - requests
        - scikit-learn
about:
    dev_url: https://github.com/knu2xs/ba-tools
    doc_source_url: https://github.com/knu2xs/ba-tools/blob/master/README.md
    doc_url: https://github.com/knu2xs/ba-tools/blob/master/README.md
    home: https://github.com/knu2xs/ba-tools
    license: Apache 2.0
    license_file: LICENSE
    summary: Address business challenges using quantitative geographic and machine
        learning methods.
extra:
    copy_test_source_files: true
    final: true
